live_config_reload = true
# tabspaces = 2

# import = ["/home/x71c9/.config/alacritty/dracula.toml"]
# import = ["/home/x71c9/.config/alacritty/custom.toml"]
# import = ["/home/x71c9/.config/alacritty/catpuccin.toml"]
import = ["/home/x71c9/.config/alacritty/rootloops.toml"]

[env]
WINIT_X11_SCALE_FACTOR = "1"

[font]
size = 10.5

[font.normal]
# family = "IBM Plex Mono"
family = "Inconsolata"
style = "Regular"

[font.bold]
family = "IBM Plex Mono"
style = "Bold"

[font.bold_italic]
family = "IBM Plex Mono"
style = "Bold Italic"

[font.italic]
family = "IBM Plex Mono"
style = "Italic"

[font.offset]
x = 0
y = 2

[scrolling]
history = 10000
multiplier = 10

[window.padding]
x = 0
y = 0

[window]
# option_as_alt = false

