[colors.cursor]
cursor = "#FF00CC"
text = "#1d1f21"

[colors.normal]
black = "#000000"
blue = "#2472c8"
cyan = "#11a8cd"
green = "#0dbc79"
magenta = "#bc3fbc"
red = "#cd3131"
white = "#e5e5e5"
yellow = "#e5e510"

[colors.primary]
background = "#000000"
foreground = "#FFFFFF"

