theme = "edge_custom"

[keys.insert]
y = { y = "xy" } # Map yy -> xy
d = { d = "xd" } # Map dd -> xd

[editor.statusline]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type", "position-percentage"]

[editor.indent-guides]
render = true
character = "╎"

[editor.whitespace.render]
tab = "all"
nbsp = "all"
space = "all"
newline = "all"

