theme = "edge_customm

[editor]
bufferlinee = "always"
line-number = "relative"

[editor.statusline]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type", "position-percentage"]

[editor.indent-guides]
render = true
character = "╎"

[editor.whitespace.render]
tab = "all"
nbsp = "all"
space = "all"
newline = "all"

